* Черновик стандарта личных сообщений
** Преамбула

Разговоры о личных сообщениях в сетях IDEC ведутся давно -- года два. Но к какому либо решению,
договоренности так и не пришли. Самая большая проблема -- это оставить IDEC простым, plaintext.
В этом документе попробуем набросать некий протип, который может быть войдет в стандарт.

** Чеклист

- [-] Описание стандарта в этом документе
  - [-] Формат бадла
  - [-] Формат сообщения на отправку
  - [-] Формат node2node API
  - [-] Формат client API
- [-] Согласие на принятие стандарта от core-team(ники с [[https://github.com/orgs/idec-net/people][Github]])
  - [-] vit1-irk
  - [-] btimofeev
  - [-] spline1986
  - [-] Difrex
- [-] Реализация PoC
  - [-] Сервер
  - [-] Клиент

** TODO Стандарт обмена

Сейчас у нас есть практически не используемые поля, такие как, tags и address.

- tags
  Теги в IDEC в сообщении представляют из себя список с разделителем ~/~.
  Так обязательные теги, которые проверяют все ноды/клиенты -- это ~ii/ok~.
  Также у нас имеется тег ответа на сообщение - ~repto/IZXhLBKJx0rhx0lXYu3L~
  Для личного сообщения предлагается добавить некий тег, например, ~xmail~
  по которому нода сможет определять, что это сообщение является личным.
- address
  Адрес сейчас не используется никак и только говорит о том, с какой ноды
  пишет человек. Предлагается исправить этот недостаток. Мы можем использовать
  адреса для отправки сообщения определенному поинту на его адрес.


*** TODO Формат бандла личного сообщения

На основе нижеизложенных фактов предлагается к рассмотрению следующий формат бандла
#+begin_src
ii/ok/repto/IZXhLBKJx0rhx0lXYu3L/xmail # Тут мы проставлем тег ответа, а так же сообщаем, что сообщение является личным
dynamic,1                              # Вместо эхи мы используем адрес поинта, кому предназначено это сообщение
1455789357                             # Время сообщения в unixtime
Vasya                                  # Имя пользователя, которому предназначенно сообщение
Lunar, 2                               # Адрес поинта отправившего сообщение
Pupkin                                 # Имя пользователя отправившего сообщение
Re: Мое первое сообщение в эху         # Заголовок сообщения
                                       # Пустая строка
текст сообщения                        # Текст сообщения
#+end_src

*** TODO Формат сообщения на отправку

#+begin_src
dynamic,1                                      # Вместо эхи используем адрес
Vasya                                          # Имя пользователя, которому предназначено сообщение
Тестируем                                      # Заголовок сообщения
                                               # Пустая строка
@repto:2hEUbMAxKSA83vcmgU4s                    # Проставляем тег ответа, либо строка относится к телу сообщения
И вот я пишу своё первое письмо в нашу секту.  # Текст
Меня видно?                                    # сообщения
#+end_src

*** TODO Формат node2node API

*** TODO Формат client API
